### ISSUE TITLE
Error reading from database

### ISSUE THREAD

**Issue by fiercebrake** [jpahullo/moodle-tool_mergeusers#210]
Greetings everyone!

I am getting an "Error reading from database" error when opening the tool at this link "https://some.domain.i.use/admin/tool/mergeusers/index.php", meaning i don't even get to the actual merge form.

Atfirst, i was getting this error:

"Debug info: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"mdl_%"' at line 1
SHOW TABLES like "mdl_%"
[array (
)]
Error code: dmlreadexception"

For that, I made some simple changes at "admin/tool/mergeusers/lib/mergeusertool.php"

But now I am getting this:
"SELECT DISTINCT column_name
FROM
INFORMATION_SCHEMA.Columns
WHERE
TABLE_NAME = ? AND
(TABLE_SCHEMA = ? OR TABLE_CATALOG=?) AND
COLUMN_NAME IN ()
[array (
0 =&gt; 'mdl_appraisal',
1 =&gt; 'some_db_name',
2 =&gt; 'some_db_name',
)]
Error code: dmlreadexception"

WHere it seems the '$userFields' variable is coming in empty.

At this point I stopped modifying stuff and submitted this help request.

ANy advise anyone can share ?

**Comment by jpahullo** [comment]
Hi @fiercebrake,

Thanks for contacting. Which version of the plugin are you using?

The stack trace would be helpful in this cases.

Let me know.

**Comment by jpahullo** [comment]
Closing as not more feedback provided.

Thanks for reporting.

Jordi
