### ISSUE TITLE
Request: Please include an ongoing changelog instead of one file for each git tag

### ISSUE THREAD

**Issue by danowar2k** [jpahullo/moodle-tool_mergeusers#245]
It would be very nice of you to do the changelog in this way: https://keepachangelog.com/en/1.1.0/

Right now it seems you add a changes.md for each tag and put only that tag's changes in there.

If the changelog would be continuous, other people could more easily identify the differences over time.

**Comment by jpahullo** [comment]
Hi @danowar2k!

It seems interesting. The way we currently do the changes.md is somehow interpreted from the Moodle API for pushing new plugin versions. 

I can see the need. Let me know about it a bit!

thanks for the feedback

Jordi

**Comment by danowar2k** [comment]
https://moodle.org/plugins/theme_boost_union/v4.1-r6/28792 This plugin, for example, just extends its changelog for each Moodle release. Which is totally fine for users and can be automated the same way ;-)

**Comment by jpahullo** [comment]
This will be provided through the new changes under tags/releases from the master branch.

Thanks for reporting this.
