### ISSUE TITLE
FR: Option to skip over orphan grades

### ISSUE THREAD

**Issue by Fragonite** [jpahullo/moodle-tool_mergeusers#255]
A client is attempting to merge users with grades that reference activities that no longer exist. I understand this is a database issue but an option to skip over these grades (with an appropriate warning) could be useful.

This option could be implemented on the user selection screen or the plugin settings. Let us know what you think. If you are happy with this proposal, we can submit a pull request.

This relates to #189.

**Comment by jpahullo** [comment]
Thanks for the feedback.

If I understand it properly, this edge case should be considered into the
current implementation of merging grades into the plugin. This plugin tries
hard to cover all cases, also edge cases. But for sure there are lots
uncovered.

I like the idea of having implemented the way of loading customized
settings.

It would be very welcome to receive a PR for both: considering grades edge
cases into the current implementation, and also the function into lib.php
files. However, keep loading config.local.php for backwards compatibility.

Thanks!!!

**Comment by jpahullo** [comment]
Sorry, I misread that #189 was another ticket, but actually it is about
SCORM activities.

Thanks for the feedback.

Jordi

**Comment by jpahullo** [comment]
Hi @Fragonite,

I have just closed #158. Therefore, I think this issue may follow the same path.

Thanks for the interest and reporting.

Jordi
